const fs = require('fs');
const path = require('path');

// Parse .env file manually (no extra deps needed)
function loadEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  return fs.readFileSync(filePath, 'utf8')
    .split('\n')
    .filter(line => line.trim() && !line.startsWith('#'))
    .reduce((acc, line) => {
      const [key, ...rest] = line.split('=');
      acc[key.trim()] = rest.join('=').trim();
      return acc;
    }, {});
}

const env = loadEnv(path.resolve(__dirname, '.env'));

const isProd = process.argv.includes('--prod');

const content = `// Auto-generated by set-env.js — do not edit manually
export const environment = {
  production: ${isProd},
  appName: 'Foodies',
  apiUrl: '${env.API_URL || 'http://localhost:5000/api'}'
};
`;

const outDir = path.resolve(__dirname, 'src/environments');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'environment.ts'), content);
if (isProd) {
  fs.writeFileSync(path.join(outDir, 'environment.prod.ts'), content);
}

console.log(`environment.ts generated (production=${isProd}, apiUrl=${env.API_URL})`);
