"""add is_seller and seller_type to users

Revision ID: 028ff7d8febe
Revises: dc3f64683bb9
Create Date: 2026-04-04 16:02:23.870641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028ff7d8febe'
down_revision = 'dc3f64683bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seller_type', sa.Enum('homemade', 'restaurant'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('seller_type')
        batch_op.drop_column('is_seller')

    # ### end Alembic commands ###
