"""add created_at to dishes

Revision ID: 3922645ca6c4
Revises: 028ff7d8febe
Create Date: 2026-04-04 17:00:25.569791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3922645ca6c4'
down_revision = '028ff7d8febe'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'created_at', sa.DateTime(),
            nullable=False,
            server_default=sa.text('NOW()')
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
