"""add sold_count to dishes

Revision ID: 5549eb83fa0d
Revises: c198a01c8538
Create Date: 2026-04-05 01:02:48.468801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5549eb83fa0d'
down_revision = 'c198a01c8538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('sold_count')

    # ### end Alembic commands ###
