"""remove seller_type from users

Revision ID: 5c4a1991c5e5
Revises: 6b51bc38cdb2
Create Date: 2026-04-05 13:32:26.641870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c4a1991c5e5'
down_revision = '6b51bc38cdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('seller_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_type', mysql.ENUM('homemade', 'restaurant'), nullable=True))

    # ### end Alembic commands ###
