"""add seller_type to business_profiles

Revision ID: 6b51bc38cdb2
Revises: 5549eb83fa0d
Create Date: 2026-04-05 13:19:14.869981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b51bc38cdb2'
down_revision = '5549eb83fa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_type', sa.Enum('homemade', 'restaurant'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_profiles', schema=None) as batch_op:
        batch_op.drop_column('seller_type')

    # ### end Alembic commands ###
