"""add dish_settings and expires_at to dishes

Revision ID: 77b2a9014966
Revises: 96b5a1187104
Create Date: 2026-04-04 17:14:32.680473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b2a9014966'
down_revision = '96b5a1187104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
