"""migrate payment to stripe

Revision ID: c198a01c8538
Revises: e9a115d001bb
Create Date: 2026-04-05 00:36:42.164365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c198a01c8538'
down_revision = 'e9a115d001bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_client_secret', sa.String(length=255), nullable=True))
        batch_op.drop_column('razorpay_order_id')
        batch_op.drop_column('razorpay_payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_payment_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_order_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('stripe_client_secret')
        batch_op.drop_column('stripe_payment_intent_id')

    # ### end Alembic commands ###
